PREFIX dbpprop: <http://dbpedia.org/property/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?var ?var0 ?var1 ?var5 ?var10 ?var11
WHERE {
  ?var0 rdfs:comment ?var1 . ?var0 foaf:page ?var . OPTIONAL { ?var0 dbpprop:industry ?var5 . BIND (1 AS ?optvar0_) . } OPTIONAL { ?var0 dbpprop:products ?var11 . ?var0 dbpprop:model ?var0 . BIND (1 AS ?optvar1_) . } OPTIONAL { ?var0 <http://www.georss.org/georss/point> ?var10 . BIND (1 AS ?optvar2_) . }
  BIND(EXISTS { ?opt_var0 rdfs:comment ?opt_var1 . ?opt_var0 foaf:page ?opt_var . ?opt_var0 dbpprop:industry ?opt_var5 . } AS ?optgroup1_) . BIND(EXISTS { ?opt_var0 rdfs:comment ?opt_var1 . ?opt_var0 foaf:page ?opt_var . ?opt_var0 dbpprop:products ?opt_var11 . ?opt_var0 dbpprop:model ?opt_var0 . } AS ?optgroup2_) . BIND(EXISTS { ?opt_var0 rdfs:comment ?opt_var1 . ?opt_var0 foaf:page ?opt_var . ?opt_var0 dbpprop:industry ?opt_var5 . ?opt_var0 dbpprop:products ?opt_var11 . ?opt_var0 dbpprop:model ?opt_var0 . } AS ?optgroup3_) . BIND(EXISTS { ?opt_var0 rdfs:comment ?opt_var1 . ?opt_var0 foaf:page ?opt_var . ?opt_var0 <http://www.georss.org/georss/point> ?opt_var10 . } AS ?optgroup4_) . BIND(EXISTS { ?opt_var0 rdfs:comment ?opt_var1 . ?opt_var0 foaf:page ?opt_var . ?opt_var0 dbpprop:industry ?opt_var5 . ?opt_var0 <http://www.georss.org/georss/point> ?opt_var10 . } AS ?optgroup5_) . BIND(EXISTS { ?opt_var0 rdfs:comment ?opt_var1 . ?opt_var0 foaf:page ?opt_var . ?opt_var0 dbpprop:products ?opt_var11 . ?opt_var0 dbpprop:model ?opt_var0 . ?opt_var0 <http://www.georss.org/georss/point> ?opt_var10 . } AS ?optgroup6_) . BIND(EXISTS { ?opt_var0 rdfs:comment ?opt_var1 . ?opt_var0 foaf:page ?opt_var . ?opt_var0 dbpprop:industry ?opt_var5 . ?opt_var0 dbpprop:products ?opt_var11 . ?opt_var0 dbpprop:model ?opt_var0 . ?opt_var0 <http://www.georss.org/georss/point> ?opt_var10 . } AS ?optgroup7_) .
  FILTER (!?optgroup1_ || ((BOUND(?optvar0_)))) FILTER (!?optgroup2_ || (((BOUND(?optvar1_))) || (BOUND(?optvar0_)))) FILTER (!?optgroup3_ || ((BOUND(?optvar0_)) && ((BOUND(?optvar1_))))) FILTER (!?optgroup4_ || ((((BOUND(?optvar2_))) || (BOUND(?optvar1_))) || (BOUND(?optvar0_)))) FILTER (!?optgroup5_ || ((BOUND(?optvar0_)) && (((BOUND(?optvar2_))) || (BOUND(?optvar1_))))) FILTER (!?optgroup6_ || (((BOUND(?optvar1_)) && ((BOUND(?optvar2_)))) || (BOUND(?optvar0_)))) FILTER (!?optgroup7_ || ((BOUND(?optvar0_)) && ((BOUND(?optvar1_)) && ((BOUND(?optvar2_))))))
}