PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?company ?uri ?parent ?place
WHERE {
  ?company rdf:type dbo:Organisation . ?uri dbo:developer ?company . OPTIONAL { ?company dbo:parentCompany ?parent . BIND (1 AS ?optvar0_) . } OPTIONAL { ?uri rdf:type dbo:Software . BIND (1 AS ?optvar1_) . } OPTIONAL { ?company dbo:foundationPlace ?place . BIND (1 AS ?optvar2_) . }
  BIND(EXISTS { ?opt_company rdf:type dbo:Organisation . ?opt_uri dbo:developer ?opt_company . ?opt_company dbo:parentCompany ?opt_parent . } AS ?optgroup1_) . BIND(EXISTS { ?opt_company rdf:type dbo:Organisation . ?opt_uri dbo:developer ?opt_company . ?opt_uri rdf:type dbo:Software . } AS ?optgroup2_) . BIND(EXISTS { ?opt_company rdf:type dbo:Organisation . ?opt_uri dbo:developer ?opt_company . ?opt_company dbo:parentCompany ?opt_parent . ?opt_uri rdf:type dbo:Software . } AS ?optgroup3_) . BIND(EXISTS { ?opt_company rdf:type dbo:Organisation . ?opt_uri dbo:developer ?opt_company . ?opt_company dbo:foundationPlace ?opt_place . } AS ?optgroup4_) . BIND(EXISTS { ?opt_company rdf:type dbo:Organisation . ?opt_uri dbo:developer ?opt_company . ?opt_company dbo:parentCompany ?opt_parent . ?opt_company dbo:foundationPlace ?opt_place . } AS ?optgroup5_) . BIND(EXISTS { ?opt_company rdf:type dbo:Organisation . ?opt_uri dbo:developer ?opt_company . ?opt_uri rdf:type dbo:Software . ?opt_company dbo:foundationPlace ?opt_place . } AS ?optgroup6_) . BIND(EXISTS { ?opt_company rdf:type dbo:Organisation . ?opt_uri dbo:developer ?opt_company . ?opt_company dbo:parentCompany ?opt_parent . ?opt_uri rdf:type dbo:Software . ?opt_company dbo:foundationPlace ?opt_place . } AS ?optgroup7_) .
  FILTER (!?optgroup1_ || ((BOUND(?optvar0_)))) FILTER (!?optgroup2_ || (((BOUND(?optvar1_))) || (BOUND(?optvar0_)))) FILTER (!?optgroup3_ || ((BOUND(?optvar0_)) && ((BOUND(?optvar1_))))) FILTER (!?optgroup4_ || ((((BOUND(?optvar2_))) || (BOUND(?optvar1_))) || (BOUND(?optvar0_)))) FILTER (!?optgroup5_ || ((BOUND(?optvar0_)) && (((BOUND(?optvar2_))) || (BOUND(?optvar1_))))) FILTER (!?optgroup6_ || (((BOUND(?optvar1_)) && ((BOUND(?optvar2_)))) || (BOUND(?optvar0_)))) FILTER (!?optgroup7_ || ((BOUND(?optvar0_)) && ((BOUND(?optvar1_)) && ((BOUND(?optvar2_))))))
}