PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX res: <http://dbpedia.org/resource/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?uri ?actor ?actor2 ?parent ?spouse ?partner
WHERE {
  ?uri rdf:type dbo:Film . ?uri dbo:starring ?actor . ?uri dbo:starring ?actor2. FILTER(?actor != ?actor2) . OPTIONAL { ?actor dbo:parent ?actor2 . BIND(1 AS ?parent) . BIND (1 AS ?optvar0_) . } OPTIONAL { ?actor dbo:spouse ?actor2 . BIND(1 AS ?spouse) . BIND (1 AS ?optvar1_) . } OPTIONAL { ?actor dbo:partner ?actor2 . BIND(1 AS ?partner) . BIND (1 AS ?optvar2_) . }
  BIND(EXISTS { ?opt_uri rdf:type dbo:Film . ?opt_uri dbo:starring ?opt_actor . ?opt_uri dbo:starring ?opt_actor2. FILTER(?opt_actor != ?opt_actor2) . ?opt_actor dbo:parent ?opt_actor2 . BIND(1 AS ?opt_parent) . } AS ?optgroup1_) . BIND(EXISTS { ?opt_uri rdf:type dbo:Film . ?opt_uri dbo:starring ?opt_actor . ?opt_uri dbo:starring ?opt_actor2. FILTER(?opt_actor != ?opt_actor2) . ?opt_actor dbo:spouse ?opt_actor2 . BIND(1 AS ?opt_spouse) . } AS ?optgroup2_) . BIND(EXISTS { ?opt_uri rdf:type dbo:Film . ?opt_uri dbo:starring ?opt_actor . ?opt_uri dbo:starring ?opt_actor2. FILTER(?opt_actor != ?opt_actor2) . ?opt_actor dbo:parent ?opt_actor2 . BIND(1 AS ?opt_parent) . ?opt_actor dbo:spouse ?opt_actor2 . BIND(1 AS ?opt_spouse) . } AS ?optgroup3_) . BIND(EXISTS { ?opt_uri rdf:type dbo:Film . ?opt_uri dbo:starring ?opt_actor . ?opt_uri dbo:starring ?opt_actor2. FILTER(?opt_actor != ?opt_actor2) . ?opt_actor dbo:partner ?opt_actor2 . BIND(1 AS ?opt_partner) . } AS ?optgroup4_) . BIND(EXISTS { ?opt_uri rdf:type dbo:Film . ?opt_uri dbo:starring ?opt_actor . ?opt_uri dbo:starring ?opt_actor2. FILTER(?opt_actor != ?opt_actor2) . ?opt_actor dbo:parent ?opt_actor2 . BIND(1 AS ?opt_parent) . ?opt_actor dbo:partner ?opt_actor2 . BIND(1 AS ?opt_partner) . } AS ?optgroup5_) . BIND(EXISTS { ?opt_uri rdf:type dbo:Film . ?opt_uri dbo:starring ?opt_actor . ?opt_uri dbo:starring ?opt_actor2. FILTER(?opt_actor != ?opt_actor2) . ?opt_actor dbo:spouse ?opt_actor2 . BIND(1 AS ?opt_spouse) . ?opt_actor dbo:partner ?opt_actor2 . BIND(1 AS ?opt_partner) . } AS ?optgroup6_) . BIND(EXISTS { ?opt_uri rdf:type dbo:Film . ?opt_uri dbo:starring ?opt_actor . ?opt_uri dbo:starring ?opt_actor2. FILTER(?opt_actor != ?opt_actor2) . ?opt_actor dbo:parent ?opt_actor2 . BIND(1 AS ?opt_parent) . ?opt_actor dbo:spouse ?opt_actor2 . BIND(1 AS ?opt_spouse) . ?opt_actor dbo:partner ?opt_actor2 . BIND(1 AS ?opt_partner) . } AS ?optgroup7_) .
  FILTER (!?optgroup1_ || ((BOUND(?optvar0_)))) FILTER (!?optgroup2_ || (((BOUND(?optvar1_))) || (BOUND(?optvar0_)))) FILTER (!?optgroup3_ || ((BOUND(?optvar0_)) && ((BOUND(?optvar1_))))) FILTER (!?optgroup4_ || ((((BOUND(?optvar2_))) || (BOUND(?optvar1_))) || (BOUND(?optvar0_)))) FILTER (!?optgroup5_ || ((BOUND(?optvar0_)) && (((BOUND(?optvar2_))) || (BOUND(?optvar1_))))) FILTER (!?optgroup6_ || (((BOUND(?optvar1_)) && ((BOUND(?optvar2_)))) || (BOUND(?optvar0_)))) FILTER (!?optgroup7_ || ((BOUND(?optvar0_)) && ((BOUND(?optvar1_)) && ((BOUND(?optvar2_))))))
}