PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX res: <http://dbpedia.org/resource/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?uri ?actor ?actor2 ?parent ?spouse ?partner
WHERE {
  ?uri rdf:type dbo:Film . ?uri dbo:starring ?actor . ?uri dbo:starring ?actor2. FILTER(?actor != ?actor2) .
  {
    { BIND (0 AS ?optlevel_) . } UNION { ?actor dbo:parent ?actor2 . BIND(1 AS ?parent) . BIND (1 AS ?optlevel_) . } UNION { ?actor dbo:spouse ?actor2 . BIND(1 AS ?spouse) . BIND (2 AS ?optlevel_) . } UNION { ?actor dbo:parent ?actor2 . BIND(1 AS ?parent) . ?actor dbo:spouse ?actor2 . BIND(1 AS ?spouse) . BIND (3 AS ?optlevel_) . } UNION { ?actor dbo:partner ?actor2 . BIND(1 AS ?partner) . BIND (4 AS ?optlevel_) . } UNION { ?actor dbo:parent ?actor2 . BIND(1 AS ?parent) . ?actor dbo:partner ?actor2 . BIND(1 AS ?partner) . BIND (5 AS ?optlevel_) . } UNION { ?actor dbo:spouse ?actor2 . BIND(1 AS ?spouse) . ?actor dbo:partner ?actor2 . BIND(1 AS ?partner) . BIND (6 AS ?optlevel_) . } UNION { ?actor dbo:parent ?actor2 . BIND(1 AS ?parent) . ?actor dbo:spouse ?actor2 . BIND(1 AS ?spouse) . ?actor dbo:partner ?actor2 . BIND(1 AS ?partner) . BIND (7 AS ?optlevel_) . }
  }
  BIND(EXISTS { ?opt_uri rdf:type dbo:Film . ?opt_uri dbo:starring ?opt_actor . ?opt_uri dbo:starring ?opt_actor2. FILTER(?opt_actor != ?opt_actor2) . ?opt_actor dbo:parent ?opt_actor2 . BIND(1 AS ?opt_parent) . } AS ?optgroup1_) . BIND(EXISTS { ?opt_uri rdf:type dbo:Film . ?opt_uri dbo:starring ?opt_actor . ?opt_uri dbo:starring ?opt_actor2. FILTER(?opt_actor != ?opt_actor2) . ?opt_actor dbo:spouse ?opt_actor2 . BIND(1 AS ?opt_spouse) . } AS ?optgroup2_) . BIND(EXISTS { ?opt_uri rdf:type dbo:Film . ?opt_uri dbo:starring ?opt_actor . ?opt_uri dbo:starring ?opt_actor2. FILTER(?opt_actor != ?opt_actor2) . ?opt_actor dbo:parent ?opt_actor2 . BIND(1 AS ?opt_parent) . ?opt_actor dbo:spouse ?opt_actor2 . BIND(1 AS ?opt_spouse) . } AS ?optgroup3_) . BIND(EXISTS { ?opt_uri rdf:type dbo:Film . ?opt_uri dbo:starring ?opt_actor . ?opt_uri dbo:starring ?opt_actor2. FILTER(?opt_actor != ?opt_actor2) . ?opt_actor dbo:partner ?opt_actor2 . BIND(1 AS ?opt_partner) . } AS ?optgroup4_) . BIND(EXISTS { ?opt_uri rdf:type dbo:Film . ?opt_uri dbo:starring ?opt_actor . ?opt_uri dbo:starring ?opt_actor2. FILTER(?opt_actor != ?opt_actor2) . ?opt_actor dbo:parent ?opt_actor2 . BIND(1 AS ?opt_parent) . ?opt_actor dbo:partner ?opt_actor2 . BIND(1 AS ?opt_partner) . } AS ?optgroup5_) . BIND(EXISTS { ?opt_uri rdf:type dbo:Film . ?opt_uri dbo:starring ?opt_actor . ?opt_uri dbo:starring ?opt_actor2. FILTER(?opt_actor != ?opt_actor2) . ?opt_actor dbo:spouse ?opt_actor2 . BIND(1 AS ?opt_spouse) . ?opt_actor dbo:partner ?opt_actor2 . BIND(1 AS ?opt_partner) . } AS ?optgroup6_) . BIND(EXISTS { ?opt_uri rdf:type dbo:Film . ?opt_uri dbo:starring ?opt_actor . ?opt_uri dbo:starring ?opt_actor2. FILTER(?opt_actor != ?opt_actor2) . ?opt_actor dbo:parent ?opt_actor2 . BIND(1 AS ?opt_parent) . ?opt_actor dbo:spouse ?opt_actor2 . BIND(1 AS ?opt_spouse) . ?opt_actor dbo:partner ?opt_actor2 . BIND(1 AS ?opt_partner) . } AS ?optgroup7_) .
  FILTER (!(?optgroup1_ && ?optlevel_ in (0))) FILTER (!(?optgroup2_ && ?optlevel_ in (0))) FILTER (!(?optgroup3_ && ?optlevel_ in (0, 1, 2))) FILTER (!(?optgroup4_ && ?optlevel_ in (0))) FILTER (!(?optgroup5_ && ?optlevel_ in (0, 1, 4))) FILTER (!(?optgroup6_ && ?optlevel_ in (0, 2, 4))) FILTER (!(?optgroup7_ && ?optlevel_ in (0, 1, 2, 3, 4, 5, 6)))
}